### PR TITLE
Add chart annotations to help UI show CPU & memory requirements

### PR DESCRIPTION
**Pull request by geethub97**
https://github.com/rancher/rancher/issues/37854

### CODE REVIEW

**Review by aiyengar2 — CHANGES_REQUESTED** [review]
This PR will not resolve https://github.com/rancher/rancher/issues/37854.

`When a user installs project monitoring` here implies that the user is creating a ProjectHelmChart (ProjectMonitor) resource; this is independent of the process of **enabling** project monitoring, which is done by installing the Prometheus Federator chart.

The Prometheus Federator chart itself should not have requests for CPU / memory set so high since the chart itself does not install any CPU / memory intensive resources; it only installs a controller that manages creating Helm releases that consume that much memory / CPU.

The project-monitoring chart **should** have CPU / memory checks before install, but the annotations won't make a difference since the Helm chart is deployed by the embedded Helm Project Operator, not Apps & Marketplace.

**Comment by aiyengar2** [comment]
@geethub97 this needs to go through a design meeting with UI. I'm not sure if there's a way to fully fix this with just backend work.

**Comment by geethub97** [comment]
@aiyengar2 
https://github.com/rancher/rancher/issues/37854#issuecomment-1213557909

I spoke to @catherineluse, who attached a screenshot of the expected implementation to the ticket above, and the goal is the replicate functionality from monitoring in project monitoring.

**Comment by geethub97** [comment]
@aiyengar2 ahh okay, I'll set something up so we can discuss with the UI team

**Comment by geethub97** [comment]
closing this based on our discussion today @aiyengar2 @catherineluse

**Pull request closed without merging**
